config/routes.rb
Catarse::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: "omniauth_callbacks", passwords: :passwords }
    }
  )

  #hook for contribution
  post "/hook" => "projects/contributions#hook"

  get 'auth/failure', to: redirect('/')

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}
  end


  get "/reset_confirmation_password" => 'high_voltage/pages#show', id: 'reset_confirmation_password'
  get '/thank_you' => "static#thank_you"
  get '/contact_email' => "static#send_contact_email"

  filter :locale, exclude: /\/auth\//

  #mount CatarsePayulatam::Engine => "/", :as => "catarse_payulatam"
  mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
  mount CatarseApi::Engine => "/api", as: :catarse_api
 #mount CatarseWepay::Engine => "/", as: :catarse_wepay
  mount Dbhero::Engine => "/dbhero", as: :dbhero

  resources :bank_accounts, except: [:destroy, :index] do
    member do
      get 'confirm'
      put 'request_refund'
    end
  end

  resources :categories, only: [] do
    member do
      get :subscribe, to: 'categories/subscriptions#create'
      get :unsubscribe, to: 'categories/subscriptions#destroy'
    end
  end
  resources :auto_complete_projects, only: [:index]
  resources :auto_complete_cities, only: [:index]
  resources :projects, only: [ :index, :create, :update, :edit, :new, :show] do
    resources :accounts, only: [:create, :update]
    resources :posts, controller: 'projects/posts', only: [ :index, :destroy ]
    resources :rewards, only: [ :index ] do
      post :sort, on: :member
    end
    resources :contributions, {controller: 'projects/contributions'} do
      collection do
        get :details, to: 'projects/contribution_details#index'
        get :fallback_create, to: 'projects/contributions#create'
      end
      member do
        get 'toggle_anonymous'
        get :second_slip
      end
      put :credits_checkout, on: :member
    end

    get 'video', on: :collection
    member do
      get :reminder, to: 'projects/reminders#create'
      delete :reminder, to: 'projects/reminders#destroy'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'about_mobile'
      get 'embed_panel'
      get 'send_to_analysis'
      get 'publish'
    end
  end
  resources :users do
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :settings
      get :billing
      get :reactivate
      get :personal
      #post :create_personal
      patch :update_personal
      patch :update_work
      patch :update_bank
      #post :create_personal
      #patch :update_personal
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  get "/contact" => 'high_voltage/pages#show', id: 'contact'
  get "/faq" => 'high_voltage/pages#show', id: 'faq'
  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  get "/jobs" => 'high_voltage/pages#show', id: 'jobs'
  get "/hello" => 'high_voltage/pages#show', id: 'hello'
  get "/press" => 'high_voltage/pages#show', id: 'press'
  get "/assets" => 'high_voltage/pages#show', id: 'assets'
  get "/guides" => 'high_voltage/pages#show', id: 'guides', as: :guides
  get "/new-admin" => 'high_voltage/pages#show', id: 'new_admin'
  get "/explore" => 'high_voltage/pages#show', id: 'explore'
  get "/team" => 'high_voltage/pages#show', id: 'team'


  # User permalink profile
  constraints SubdomainConstraint do
    get "/", to: 'users#show'
  end

  # Root path should be after channel constraints
  #root to: 'explore'
  root :to => redirect('/explore')

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'push_to_online'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        get :second_slip
        put 'pay'
        put 'change_reward'
        put 'refund'
        put 'trash'
        put 'request_refund'
        put 'chargeback'
        put 'gateway_refund'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  resource :api_token, only: [:show]

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/views/catarse_bootstrap/pages/assets.html.slim
- content_for :title, t('.title')
= render 'shared/header_big', overlayer: true

.hero-assets.hero-medium
  .w-container.u-text-center
    = image_tag "icon-assets.png", class: "icon-hero"
    .u-text-center.u-marginbottom-20.fontsize-largest Marcas e selos

.w-section.section-one-column.u-margintop-40
  .w-container
    .w-row
      .w-col.w-col-2
      .w-col.w-col-8
        .fontsize-base Baixe as várias versões da logo do Catarse, assim como alguns selos para serem usados na divulgação de projetos financiados. Utilize esse material para promover e compartilhar sua experiência no financiamento coletivo, de modo a ilustrar corretamente o papel do Catarse em relação ao seu projeto.
      .w-col.w-col-2
.w-section.section.u-margintop-40
  .w-container
    .fontsize-large.fontweight-semibold.u-marginbottom-30.u-text-center-small-only Logo horizontal
    .w-row.u-text-center
      .w-col.w-col-3.w-col-small-6.u-marginbottom-20
        = image_tag "assets-catarse/asset-logo-horizontal-1.jpg", class: "u-marginbottom-10"
        .fontsize-smaller
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-h-cor-positivo.png" target="_blank"  PNG (bitmap)
          | &nbsp;&nbsp;|&nbsp;&nbsp;
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-h-cor-positivo.eps" target="_blank"  EPS&nbsp;(vetor)
      .w-col.w-col-3.w-col-small-6.u-marginbottom-20
        = image_tag "assets-catarse/asset-logo-horizontal-3.jpg", class: "u-marginbottom-10"
        .fontsize-smaller
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-h-pb-positivo.png" target="_blank"  PNG (bitmap)
          | &nbsp;&nbsp;|&nbsp;&nbsp;
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-h-pb-positivo.eps" target="_blank"  EPS&nbsp;(vetor)
      .w-col.w-col-3.w-col-small-6.u-marginbottom-20
        = image_tag "assets-catarse/asset-logo-horizontal-2.jpg", class: "u-marginbottom-10"        
        .fontsize-smaller
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-h-cor-negativo.png" target="_blank"  PNG (bitmap)
          | &nbsp;&nbsp;|&nbsp;&nbsp;
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-h-cor-negativo.eps" target="_blank"  EPS&nbsp;(vetor)
      .w-col.w-col-3.w-col-small-6.u-marginbottom-20
        = image_tag "assets-catarse/asset-logo-horizontal-4.jpg", class: "u-marginbottom-10"        
        .fontsize-smaller
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-h-pb-negativo.png" target="_blank"  PNG (bitmap)
          | &nbsp;&nbsp;|&nbsp;&nbsp;
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-h-pb-negativo.eps" target="_blank"  EPS&nbsp;(vetor)
.w-section.section.u-margintop-40
  .w-container
    .fontsize-large.fontweight-semibold.u-marginbottom-30.u-text-center-small-only Logo vertical
    .w-row.u-text-center
      .w-col.w-col-3.w-col-small-6.u-marginbottom-20
        = image_tag "assets-catarse/asset-logo-vertical-1.jpg", class: "u-marginbottom-10"        
        .fontsize-smaller
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-v-cor-positivo.png" target="_blank"  PNG (bitmap)
          | &nbsp;&nbsp;|&nbsp;&nbsp;
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-v-cor-positivo.eps" target="_blank"  EPS&nbsp;(vetor)
      .w-col.w-col-3.w-col-small-6.u-marginbottom-20
        = image_tag "assets-catarse/asset-logo-vertical-3.jpg", class: "u-marginbottom-10"        
        .fontsize-smaller
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-v-pb-positivo.png" target="_blank"  PNG (bitmap)
          | &nbsp;&nbsp;|&nbsp;&nbsp;
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-v-pb-positivo.eps" target="_blank"  EPS&nbsp;(vetor)
      .w-col.w-col-3.w-col-small-6.u-marginbottom-20
        = image_tag "assets-catarse/asset-logo-vertical-2.jpg", class: "u-marginbottom-10"        
        .fontsize-smaller
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-v-cor-negativo.png" target="_blank"  PNG (bitmap)
          | &nbsp;&nbsp;|&nbsp;&nbsp;
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-v-cor-negativo.eps" target="_blank"  EPS&nbsp;(vetor)
      .w-col.w-col-3.w-col-small-6.u-marginbottom-20
        = image_tag "assets-catarse/asset-logo-vertical-4.jpg", class: "u-marginbottom-10"        
        .fontsize-smaller
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-v-pb-negativo.png" target="_blank"  PNG (bitmap)
          | &nbsp;&nbsp;|&nbsp;&nbsp;
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/logo-v-pb-negativo.eps" target="_blank"  EPS&nbsp;(vetor)
.w-section.section.u-margintop-40.u-marginbottom-60
  .w-container
    .fontsize-large.fontweight-semibold.u-marginbottom-30.u-text-center-small-only Selos
    .w-row.u-text-center
      .w-col.w-col-4.w-col-small-4.u-marginbottom-20
        = image_tag "assets-catarse/asset-selo-1.jpg", class: "u-marginbottom-10"        
        .fontsize-smaller
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/selo-cor-positivo.png" target="_blank"  PNG (bitmap)
          | &nbsp;&nbsp;|&nbsp;&nbsp;
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/selo-cor-positivo.eps" target="_blank"  EPS&nbsp;(vetor)
      .w-col.w-col-4.w-col-small-4.u-marginbottom-20
        = image_tag "assets-catarse/asset-selo-2.jpg", class: "u-marginbottom-10"        
        .fontsize-smaller
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/selo-cor-negativo.png" target="_blank"  PNG (bitmap)
          | &nbsp;&nbsp;|&nbsp;&nbsp;
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/selo-cor-negativo.eps" target="_blank"  EPS&nbsp;(vetor)
      .w-col.w-col-4.w-col-small-4.u-marginbottom-20
        = image_tag "assets-catarse/asset-selo-3.jpg", class: "u-marginbottom-10"        
        .fontsize-smaller
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/selo-verde.png" target="_blank"  PNG (bitmap)
          | &nbsp;&nbsp;|&nbsp;&nbsp;
          a.alt-link href="https://s3.amazonaws.com/cdn.catarse/assets/selo-verde.eps" target="_blank"  EPS&nbsp;(vetor)
.w-section.section.u-text-center
  .w-container
    .w-row
      .w-col.w-col-4
      .w-col.w-col-4
        a.btn.btn-dark.btn-large.u-marginbottom-20 href="https://s3.amazonaws.com/cdn.catarse/assets/assets-catarse.zip" target="_blank"  
          span.fa.fa-download
          | &nbsp;&nbsp;&nbsp;Baixar tudo
        .fontsize-small Todos os logos e selos acima juntos em um arquivo ZIP!
      .w-col.w-col-4

= render 'shared/footer_big'

app/views/catarse_bootstrap/pages/bad_browser.html.slim
- chrome_url = "http://www.google.com/chrome/"
- firefox_url = "http://www.mozilla.org/firefox/"
- content_for :title, t('.title')
= render 'devise/shared/header'
.row
  .large-5.large-centered.columns
    .box.animated.fadeIn
      h2.text-center= t('.title')
      hr
      .large-11.columns.large-centered
        p= t('.text')
      .browser-icons.large-12.columns.large-centered
        .large-6.columns.text-center
          = link_to chrome_url, target: :blank do
            = image_tag "browser_logos/chrome.png"
        .large-6.columns.text-center
          = link_to firefox_url, target: :blank do
            = image_tag "browser_logos/firefox.png"
        .large-6.columns.text-center
          = link_to "Download Chrome", chrome_url, target: :blank, class: "button action medium"
        .large-6.columns.text-center
          = link_to "Download Firefox", firefox_url, target: :blank, class: "button action medium"

app/views/catarse_bootstrap/pages/contact.html.slim
 - content_for "Contacto"

 = render 'shared/header_big'
 .w-section
 	.w-container    
    	.w-row
    		.w-col.w-col-10.w-col-push-1
    			.w-form.card.card-terciary.u-marginbottom-20
    				.fontsize-base.fontweight-semibold
    					| Contacto
    				.divider.u-marginbottom-20
                     - if flash[:alert].present?
                          .card.card-error.u-radius.zindex-10.u-marginbottom-30
                            .fontsize-smaller.fontweight-bold.u-marginbottom-10= t('failure_title')
                            .fontsize-smaller = flash[:alert]
                    = render 'layouts/flash' if notice.present?
    				= form_tag "/contact_email", method: "get" do
                        .w-row
        					.w-col.w-col-12.w-sub-col
        						label.text.required.field-label.field-label.fontweight-semibold.force-text-dark Direccion:
        						label.text.required.field-label.field-label.fontweight-semibold.force-text-dark Carrera 7 # 29-34 Oficina 701 - Bogotá (Colombia)
        					.w-col.w-col-12.w-sub-col
        						label.text.required.field-label.field-label.fontweight-semibold.force-text-dark Telefono:
                                label.text.required.field-label.field-label.fontweight-semibold.force-text-dark 7443254
    						.w-col.w-col-12.w-sub-col
        						label.text.required.field-label.field-label.fontweight-semibold.force-text-dark Correo:
                                label.text.required.field-label.field-label.fontweight-semibold.force-text-dark info@homeparte.com
        				.w-row

                          iframe width="600" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:EiBDcmEuIDcgIzI5LTM0LCBCb2dvdMOhLCBDb2xvbWJpYQ&key=AIzaSyBmtpykEj79ALb2D23rSCkivK3SiFmY3vM" allowfullscreen

 = render 'shared/footer_big'

app/views/catarse_bootstrap/pages/explore.html.slim
- content_for :title, t('.title')
- categories = Category.with_projects.order(:name_pt).all
= render 'shared/header_big', overlayer: true

- if current_user
  #nearOfData data-state="#{current_user.address_state}"

= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js'
= javascript_include_tag "https://code.jquery.com/jquery-1.11.0.min.js"
= javascript_include_tag "https://code.jquery.com/jquery-migrate-1.2.1.min.js"


= render 'home/slider'
= render 'home/channel'
= render 'home/definition'
= render 'home/process'
= render 'home/projects'
= render 'home/invest'
= render 'home/start'

= render 'shared/footer_big'


= javascript_include_tag "homeparte.js"

app/views/catarse_bootstrap/pages/hello.html.slim
- content_for :title, t('.page-title')
= render 'shared/header_big', overlayer: true



.hero-hello
  .w-embed.w-hidden-medium.w-hidden-small.w-hidden-tiny
    video poster=image_path("hero-hello.jpg") autoplay="" loop="" style=("width:100%; height: auto; position:absolute; z-index: -1;") 
      source src="https://s3.amazonaws.com/cdn.catarse/assets/background-video.mp4" type="video/mp4" 
  .hero-content
    a.w-lightbox.w-inline-block.btn-play href="#" 
      = image_tag "play-hero-green.svg"
    .fontweight-semibold.u-marginbottom-20.fontsize-megajumbo = t('.hero.title')
  .knowmore-hello 
    .fa.fa-chevron-down.fontcolor-dashboard
.section-large.hello-idea
  .w-container
    .w-row
      .w-col.w-col-10.w-col-push-1
        .u-marginbottom-20
          = image_tag "lampada-white.png", class: "icon-hello-sm"
        .u-marginbottom-20
          = image_tag "marcio-avatar.jpg", class: "thumb.big u-round"
        .fontweight-semibold.fontsize-jumbo.u-marginbottom-20 = t('.idea.title')
        .fontsize-large.fontcolor-negative.u-marginbottom-40 = t('.idea.subtitle')
.section-large.hello-catarse
  .w-container
    .w-row.section-large
      .w-col.w-col-10.w-col-push-1
        = image_tag "icon-fincol.png", class: "icon-hello-lg"
        .fontweight-semibold.fontsize-jumbo.u-marginbottom-20 = t('.fund.title')
        .fontsize-large.u-marginbottom-40 = t('.fund.subtitle')
    .w-row.section-large
      .w-col.w-col-10.w-col-push-1
        = image_tag "icon-campanha.png", class: "icon-hello-lg"        
        .fontweight-semibold.fontsize-jumbo.u-marginbottom-20 = t('.campaign.title')
        .fontsize-large.u-marginbottom-40 = t('.campaign.subtitle') 
    .w-row.section-large
      .w-col.w-col-10.w-col-push-1
        = image_tag "icon-tudonada.png", class: "icon-hello-md"        
        .fontweight-semibold.fontsize-jumbo.u-marginbottom-20 = t('.allornothing.title')
        .fontsize-large.u-marginbottom-40 = t('.allornothing.subtitle')
.u-text-center.section-large
  .w-container
    .w-row
      .w-col.w-col-10.w-col-push-1
        = image_tag "proceso.png", class: "w-hidden-small w-hidden-tiny u-marginbottom-20", width: "76%"                
        .fontweight-semibold.fontsize-jumbo.u-marginbottom-20 = t(".success.title")
        .fontsize-large.u-marginbottom-40 = t('.success.subtitle')
.section-large.dark
  .w-container.u-text-center
    .fontweight-semibold.fontsize-jumbo.u-marginbottom-60 = t('.cta.title')
    .w-row
      .w-col.w-col-6.right-divider
        .fontsize-large.lineheight-tight.u-marginbottom-60 = t('.cta.backer-cta') 
        a.btn.btn-large.btn-inline href="#{explore_path(ref: 'hello', anchor: 'recommended')}" = t('.cta.backer-link') 
      .w-col.w-col-6.u-marginbottom-30
        .fontsize-large.lineheight-tight.u-marginbottom-30 = t('.cta.maker-cta')
        a.btn.btn-large.btn-inline href="#{start_path(ref: 'hello')}" = t('.cta.maker-link')
.section-large.bg-humberto
  .w-container
    .w-row.u-marginbottom-20
      .w-col.w-col-10.w-col-push-1
        .fontsize-larger.u-marginbottom-40.lineheight-tight.fontcolor-negative.u-text-center-small-only = t('.testimonial.humberto.text_html')
    .u-text-center
      = image_tag "humberto-avatar.JPG", class: "thumb u-round u-marginbottom-10 big"        
      .fontweight-semibold.fontsize-large.fontcolor-negative = t('.testimonial.humberto.name') 
      .fontsize-base.fontcolor-negative = t('.testimonial.humberto.credentials')
.section-one-column.bg-gray
  .w-container.card-big.u-margintop-30.u-marginbottom-40
    = image_tag "icon-hello-1.png", width: "47", class: "u-marginbottom-20"
    .fontsize-larger.u-marginbottom-40.lineheight-tighter = t('.details.fund.title')
    .fontsize-large = t('.details.fund.text')
  .w-container.card-big.u-marginbottom-40
    = image_tag "icon-hello-2.png", width: "47", class: "u-marginbottom-20"
    .fontsize-larger.u-marginbottom-40.lineheight-tighter = t('.details.allornothing.title')
    .fontsize-large = t('.details.allornothing.text_html')
  .w-container.card-big.u-marginbottom-40
    = image_tag "icon-hello-3.png", width: "47", class: "u-marginbottom-20"
    .fontsize-larger.u-marginbottom-40.lineheight-tighter = t('.details.services.title')
    .fontsize-large = t('.details.services.text')
  .w-container.card-big.u-marginbottom-40
    = image_tag "icon-hello-4.png", width: "47", class: "u-marginbottom-20"
    .fontsize-larger.u-marginbottom-40.lineheight-tighter = t('.details.fees.title')
    .fontsize-large = t('.details.fees.text')
  .w-container.card-big
    = image_tag "icon-hello-5.png", width: "47", class: "u-marginbottom-20"
    .fontsize-larger.u-marginbottom-40.lineheight-tighter = t('.details.work.title')
    .fontsize-large = t('.details.work.text')
.section.bg-gray
  .w-container
    .w-row.u-marginbottom-80.u-text-center.u-margintop-30
      .w-col.w-col-6.right-divider
        .fontsize-large.lineheight-tight.u-marginbottom-30 = t('.cta.backer-cta')
        a.btn.btn-large.btn-inline href="#{explore_path(ref: 'hello', anchor: 'recommended')}" = t('.cta.backer-link')
      .w-col.w-col-6
        .fontsize-large.lineheight-tight.u-marginbottom-30 = t('.cta.maker-cta')
        a.btn.btn-large.btn-inline href="#{start_path(ref: 'hello')}" = t('.cta.maker-link')
.bg-people.before-footer
  .w-container
    .fontsize-large.u-text-center = t('.staff')

.w-lightbox-backdrop.w-hidden tabindex="0"
  .w-lightbox-container
    .w-lightbox-content
      .w-lightbox-view
        .w-lightbox-frame
          figure.w-lightbox-figure
            #player
            /iframe class="" width="1280" height="720" src="https://www.youtube.com/embed/cvBERv1kTL8?rel=0&amp;controls=0&amp;showinfo=0" frameborder="0" allowfullscreen
        .w-lightbox-spinner
      .w-lightbox-control.w-lightbox-close
    .w-lightbox-strip

= render 'shared/footer_big'

app/views/catarse_bootstrap/pages/new_admin.html.slim
- content_for :title, "Administre com amor <3"
- content_for :application_js do
  = javascript_include_tag 'api/application' 

= render 'shared/header_big'

#new-admin

= render 'shared/footer'

app/views/catarse_bootstrap/pages/reset_confirmation_password.html.slim
- content_for :title, t('.titles.site')
= render 'devise/shared/header'

section#pwd-recover
  .wrapper
    .table
      .container
        .container.login-container

          .card
            h2.card-title
              i.material-icons done_all
              | Acceso enviado
            p Hemos enviado a tu email un acceso para que pueda cambiar tu contraseña.
            p
              | Muchas Gracias <br>
              b HomeParte
          p.terms
            a href="#{terms_of_use_path}" target="_blank"  Términos y Condiciones
            | \
            a href="#" target="_blank"  Políticas de Privacidad

app/views/catarse_bootstrap/pages/start.html.slim
- content_for :title, t('.page-title')

= render 'shared/header_big'

.project-start-wrapper
  .page-header
    .w-container.no-responsive
      h1.fontsize-largest.u-text-center.u-marginbottom-70.u-margintop-40 = t('.title')

      .w-row.u-margintop-20.u-marginbottom-60
        .w-col.w-col-4.w-col-push-4
          = link_to t('.submit'), new_project_path, class: 'btn btn-large'

  section#learn
    .w-container.no-responsive.section
      article.w-row.u-marginbottom-80.u-margintop-30
        .w-col.w-col-6.u-text-center
          = image_tag "catarse_bootstrap/start/inscreva-seu-projeto.png"
        .w-col.w-col-6
          h2.headline = t('.start.title')
          p.fontsize-base = t('.start.content')
          

      article.w-row.u-marginbottom-80
        .w-col.w-col-6
          h2.headline = t('.people.title')
          p.fontsize-base = t('.people.content')
        .w-col.w-col-6.u-text-center
          = image_tag "catarse_bootstrap/start/trabalhe-muito.png"

      article.w-row.u-marginbottom-80
        .w-col.w-col-6.u-text-center
          = image_tag "catarse_bootstrap/start/tudo-ou-nada.png"
        .w-col.w-col-6
          h2.headline = t('.work.title')
          p.fontsize-base = t('.work.content')
          

      article.w-row.u-marginbottom-80
        .w-col.w-col-6
          h2.headline = t('.time.title')
          p.fontsize-base = t('.time.content')
        .w-col.w-col-6.u-text-center
          = image_tag "catarse_bootstrap/start/mobilze-interessados.png"

      footer.w-row.u-margin-top-40
        .w-col.w-col-4.w-col-push-4
          = link_to t('.submit'), new_project_path, class: 'btn btn-large'

  = render 'shared/footer_big'

app/views/catarse_bootstrap/pages/team.html.slim
- content_for :title, "Nuestro Equipo"
- content_for :application_js do
  = javascript_include_tag 'api/application' 

= render 'shared/header_big', overlayer: true

.w-section.hero-who.hero-full
  .w-container.u-text-center
    img.icon-hero src="/assets/logo-yellow.png" /
    .u-text-center.u-marginbottom-20.fontsize-largest Conoce a nuestro equipo

#team-root

= render 'shared/footer_big'